name = "ACE1pack"
uuid = "8c4e8d19-0bd6-4234-8309-7210652e3178"
authors = ["Christoph Ortner <christophortner0@gmail.com> and contributors"]
version = "0.5.0"

[deps]
ACE1 = "e3f9bc04-086e-409a-ba78-e9769fe067bb"
ACE1x = "5cc4c08c-8782-4a30-af6d-550b302e9707"
ACEfit = "ad31a8ef-59f5-4a01-b543-a85c2f73e95c"
ExtXYZ = "352459e4-ddd7-4360-8937-99dcb397b478"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JuLIP = "945c410c-986d-556a-acb1-167a618e0462"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
ACE1 = "0.11.1, 0.11"
ACE1x = "0.1"
ACEfit = "0.1.1"
ExtXYZ = "0.1"
JuLIP = "0.13.9, 0.14.0"
PrettyTables = "1.3, 2.0"
Reexport = "1"
StaticArrays = "1"
YAML = "0.4"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
