[deps]
ACEpotentials = "3b96b61c-0fcc-4693-95ed-1ef9f35fcc53"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
IPICalculator = "78514ca9-c0f0-4226-8c48-df09c4255a51"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
ACEpotentials = "0.10"
julia = "1.11"
