[deps]
ACE1 = "e3f9bc04-086e-409a-ba78-e9769fe067bb"
ACE1pack = "8c4e8d19-0bd6-4234-8309-7210652e3178"
ACEfit = "ad31a8ef-59f5-4a01-b543-a85c2f73e95c"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JuLIP = "945c410c-986d-556a-acb1-167a618e0462"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ACE1pack = "0.4"
Literate = "2.13.2,3"
